#this yaml file for task01 SwimUnet model


model :
    name : 'swin_transunet'
    use_checkpointing: True 
    bottleneck:
        dim: 512 
        depth: 4 
        window_shape: [4, 4, 4] 
        num_heads: 8
        shift_size: [2, 2, 2]
        
data :
    modality : 'MRI'
    val_count : 24
    train_count : 460
    num_classes : 4
    batch : 2
    num_replicas : 8
    image_shape : [240,240,155,4]
    label_shape : [240,240,155,1]
    image_patch_shape: [96, 96, 96, 4]
    label_patch_shape: [96, 96, 96, 1]
    num_patches : 32

    stage_patches_per_volume : 32 
    stage1_fg_ratio : 0.5 
    stage2_fg_ratio : 0.5 
    stage3_fg_ratio : 0.5
    stage3_hard_sample_ratio: 0.25
    stage2_intra_class_ratio : [0.128 , 0.461 , 0.411 ]
    
    dataset_url : 'https://msd-for-monai.s3-us-west-2.amazonaws.com/Task01_BrainTumour.tar'
    tarfile_name : "Task01_BrainTumour.tar"
    class_names : ['BackGround' , 'edema' , 'non-enhancing tumor' , 'enhancing tumour']
    class_weights : [1.0, 135.77891991613737, 489.1624819462532, 435.4428642924422]
    loss_weights : [1.0,1.5]
checkpoint :
    #checkpoint_dir : 'gs://medical_segmentation_decathlon/task01/swimunet/checkpoints'
    local_checkpoint_dir: '/kaggle/working/checkpoints/swimunet/'
    gcs_checkpoint_dir : 'gs://medical_segmentation_decathlon/task01/swimunet/checkpoints'

    total_step : 184000 
    warmup_step : 10 
    target_lr : 3e-4 
    min_delta : 1e-4 
    patiance : 15 
    batches_per_epoch : 920
    total_epoch : 200
    log_dir : 'gs://medical_segmentation_decathlon/task01/swimunet/logs'
    stage_2_epoch : 76
    stage_3_epoch : 151
    
optimizer : 
    starting_lr : 1e-4 
    weight_decay : 1e-5 
    
loss : 'sementic_segmetation_loss'